<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= $this->fetch('layout-styles') ?>
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="<?= $this->routeUrl('/') ?>">Home</a></li>
            </ul>
        </nav>
        <main>
            <?= $this->block('content') ?>
        </main>
        <?= $this->fetch('layout-scripts') ?>
        <?= $this->block('scripts') ?>
    </body>
</html>