<!DOCTYPE html>
<html>
    <head>
        <title>Micro PHP</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php foreach ($this->styles() as $src => $attributes): ?>
            <link rel="stylesheet" type="text/css" href="<?= url($src) ?>"<?= esc_attrs($attributes) ?>>
        <?php endforeach ?>
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="<?= route_url('/') ?>">Home</a></li>
            </ul>
        </nav>
        <main>
            <?= $this->block('content') ?>
        </main>
        <?php foreach ($this->scripts() as $src => $attributes): ?>
            <script src="<?= url($src) ?>"<?= esc_attrs($attributes) ?>></script>
        <?php endforeach ?>
        <?= $this->block('scripts') ?>
    </body>
</html>