<?php if ($pager->max() > 0): ?>
<nav class="pagination is-left is-small" role="navigation" aria-label="pagination">
<a class="pagination-previous"<?= $pager->prev() ? '' : ' disabled' ?> href="<?= route_url($pager->route(), $pager->paramsForPage($pager->page() - 1)) ?>">Previous</a>
<a class="pagination-next"<?= $pager->next() ? '' : ' disabled' ?> href="<?= route_url($pager->route(), $pager->paramsForPage($pager->page() + 1)) ?>">Next</a>
    <ul class="pagination-list">
        <?php if ($pager->start() != 0): ?>
            <li>
                <a href="<?= route_url($pager->route(), $pager->paramsForPage(0)) ?>" class="pagination-link<?= $pager->page() == 0 ? ' is-current' : '' ?>">1</a>
            </li>
        <?php endif ?>
        <?php if ($pager->hasLeftHidden()): ?>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        <?php endif ?>
        <?php for ($i = $pager->start(); $i <= $pager->end(); $i++): ?>
            <li>
                <a href="<?= route_url($pager->route(), $pager->paramsForPage($i)) ?>" class="pagination-link<?= $pager->page() == $i ? ' is-current' : '' ?>">
                    <?= $i + 1 ?>
                </a>
            </li>
        <?php endfor ?>
        <?php if ($pager->hasRightHidden()): ?>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        <?php endif ?>
        <?php if ($pager->end() != $pager->max()): ?>
            <li>
                <a href="<?= route_url($pager->route(), $pager->paramsForPage($pager->max())) ?>" class="pagination-link<?= $pager->page() == $pager->max() ? ' is-current' : '' ?>">
                    <?= $pager->max() + 1 ?>
                </a>
            </li>
        <?php endif ?>
    </ul>
</nav>
<?php endif ?>